_base_: '../Base/Base_Sup_Mono_Depth.yaml'

model:
  name: "MSDepth"
  eval_mode: 'depth' 
  mode: 'midas_small' #['midas', 'midas_small']

  # Network options  
  n_bins: 256
  min_depth: 1.0e-3
  max_depth: 100.
  norm: 'linear'
  fuse_layer: 'L1234'

  # loss option
  sup_depth_weight: 1.0 # supervised loss weight
  smooth_weight: 0 # smoothness loss weight
  consistency_weight: 0.01 # feature consistency loss weight 
  consis_idx: ['3'] # 0,1,2,3
  geometry_weight: 0.5 # geometric consistency loss weight
  consist_balance_weight: 0.5
  flag_fuse: True
  ckpt_path: './checkpoints/midas_small_align.ckpt'
